[versions]
agp = "8.5.0"
kotlin = "1.9.0"
coreKtx = "1.10.1"
appcompat = "1.6.1"
xposed = "82"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

