name: Android Build

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: rewescanmod-debug
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Release artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: rewescanmod-release
          path: app/build/outputs/apk/release/*.apk

      - name: Create Release on GitHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk
